version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/codelib_app
    ports:
      - 8000:8000
    image: app:codelib_app
    container_name: codelib_app_container
    command: python manage.py runserver 0.0.0.0:8000
