version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'codelib-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      db:
        condition: service_healthy
