# Generated by Django 3.2.14 on 2022-07-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('title',)},
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='pages.discipline')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('target_ct', models.ForeignKey(limit_choices_to={'model__in': ('discipline', 'theme')}, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
