# Generated by Django 3.2.14 on 2022-07-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220704_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='target_ct',
            new_name='parent_ct',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='target_id',
            new_name='parent_id',
        ),
    ]
