# Generated by Django 3.2.14 on 2022-07-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0003_auto_20220704_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent_ct',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='page',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('discipline', 'theme')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='page',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
