# Generated by Django 3.2.14 on 2022-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220704_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/%Y/%m/%d'),
        ),
    ]
