# Generated by Django 3.2.14 on 2022-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220705_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
