# Generated by Django 3.2.14 on 2022-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_discipline_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='created')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='pages/%Y/%m/%d')),
                ('discipline_field', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='created')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('theme_field', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
    ]
