# Generated by Django 3.2.14 on 2022-07-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_disciplineparent_themeparent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisciplineParent',
        ),
        migrations.DeleteModel(
            name='ThemeParent',
        ),
    ]
