# Generated by Django 3.2.14 on 2022-07-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20220713_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='created')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DisciplineParent',
            fields=[
                ('generalparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.generalparent')),
                ('image', models.ImageField(blank=True, upload_to='pages/%Y/%m/%d')),
                ('discipline_field', models.TextField(blank=True)),
            ],
            bases=('pages.generalparent',),
        ),
        migrations.CreateModel(
            name='ThemeParent',
            fields=[
                ('generalparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.generalparent')),
                ('theme_field', models.TextField(blank=True)),
            ],
            bases=('pages.generalparent',),
        ),
    ]
