# Generated by Django 3.2.14 on 2022-07-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_disciplineparent_generalparent_themeparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disciplineparent',
            name='generalparent_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_instance', serialize=False, to='pages.generalparent'),
        ),
        migrations.AlterField(
            model_name='themeparent',
            name='generalparent_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child2_instance', serialize=False, to='pages.generalparent'),
        ),
    ]
