# Generated by Django 3.2.14 on 2022-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_page_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='theme',
            name='path',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
