# Generated by Django 3.2.14 on 2022-07-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20220713_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='path',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='id',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='path',
        ),
        migrations.AddField(
            model_name='discipline',
            name='generalcontent_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='discipline', serialize=False, to='pages.generalcontent'),
        ),
        migrations.AddField(
            model_name='theme',
            name='generalcontent_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='theme', serialize=False, to='pages.generalcontent'),
        ),
    ]
