# Generated by Django 3.2.14 on 2022-07-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20220714_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='created',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='created',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='generalcontent_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='discipline', serialize=False, to='pages.generalcontent'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='generalcontent_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='theme', serialize=False, to='pages.generalcontent'),
        ),
    ]
