# Generated by Django 3.2.14 on 2022-07-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20220714_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='discipline',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
