# Generated by Django 3.2.14 on 2022-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeparent',
            name='generalparent_ptr',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='discipline',
            new_name='discipline_parent',
        ),
        migrations.AddField(
            model_name='theme',
            name='discipline_parent',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='DisciplineParent',
        ),
        migrations.DeleteModel(
            name='GeneralParent',
        ),
        migrations.DeleteModel(
            name='ThemeParent',
        ),
    ]
